"""Read-only native-source witnesses for the visible cinematic hair rim.

Hand-picked target pixels locate a diagnostic only; no geometry, source labels,
camera path, or foreground mask is modified or generated by this script.
"""
from pathlib import Path
import argparse
import time
import cv2
import numpy as np
import open3d as o3d
from PIL import Image, ImageDraw
from joint_temporal_texture import cameras, project, exr, display, ROOT as COLOR
from joint_temporal_texture import read, sha, atomic_json
from bake_joint_temporal_mesh import camera_depth
from diffusion_mesh_repair import scene_for

BASE = Path('/mnt/data/dec5_cinematic_wide_spiral_v3/wide_spiral_free')
OUT = Path('/mnt/data/dec5_cinematic_hair_rim_witnesses')
POINTS = [(720, 110), (744, 157), (501, 193), (289, 359), (178, 744), (710, 240)]


def signed_distance(mask):
    mask = np.asarray(mask, np.uint8)
    return cv2.distanceTransform(mask, cv2.DIST_L2, cv2.DIST_MASK_PRECISE) - cv2.distanceTransform(1-mask, cv2.DIST_L2, cv2.DIST_MASK_PRECISE)


def run():
    cv2.setNumThreads(2)
    frame = '001083'
    folder = OUT / frame
    folder.mkdir(parents=True, exist_ok=False)
    start = time.monotonic()
    q = read(BASE/'request.json')
    record = next(r for r in q['inventory'] if r['frame_id'] == frame)
    source = BASE/'frames'/frame
    receipt = read(source/'complete.json')
    assert receipt['request_sha256'] == sha(BASE/'request.json')
    for name, digest in receipt['hashes'].items():
        assert sha(source/name) == digest
    assert sha(record['mesh']) == record['mesh_sha256']
    rows, _, _ = cameras(frame)
    old = read(source/'result.json')
    assert old['source_cameras'] == [r['physical_camera'] for r in rows]
    maskroot = Path(record['source_masks']['root'])
    assert sha(maskroot/'masks.npz') == record['source_masks']['masks_sha256']
    assert sha(maskroot/'cameras.json') == record['source_masks']['cameras_sha256']
    names = read(maskroot/'cameras.json')
    original_masks = np.load(maskroot/'masks.npz')['masks']
    refined = Path('/mnt/data/dec5_uniform_measured_head_masks')/frame
    refreceipt = read(refined/'result.json')
    for name, digest in refreceipt['hashes'].items():
        assert sha(refined/name) == digest
    refnames = read(refined/'cameras.json')
    refmasks = np.load(refined/'masks.npz')['masks']
    mesh = o3d.io.read_triangle_mesh(record['mesh'])
    v, t = np.asarray(mesh.vertices, np.float32), np.asarray(mesh.triangles, np.uint32)
    depth, faces, bary = camera_depth(scene_for(v, t), record['camera'])
    np.testing.assert_array_equal(np.where(np.isfinite(depth), depth, 0), np.load(source/'target_depth.npz')['depth'])
    image = np.rot90(np.asarray(Image.open(source/'prediction_native.png')))
    ids = np.asarray(Image.open(source/'source_ids.png'))
    assert image.shape == (1920, 1080, 3)
    samples = []
    for x, y in POINTS:
        nx, ny = 1919-y, x
        if not np.isfinite(depth[ny, nx]) or ids[ny, nx] == 255:
            samples.append(dict(portrait_xy=[x, y], surface=False))
            continue
        f = int(faces[ny, nx]); b = bary[ny, nx]
        point = (v[t[f]] * np.array([1-b.sum(), b[0], b[1]], np.float32)[:, None]).sum(0)
        samples.append(dict(portrait_xy=[x, y], native_xy=[nx, ny], surface=True,
            face_id=f, source_id=int(ids[ny, nx]), point=point.tolist()))
    active = [s for s in samples if s['surface']]
    uv, z = project(np.array([s['point'] for s in active], np.float32), rows)
    distances = np.full((len(rows), len(active)), np.nan)
    original_distances = distances.copy()
    for ci, row in enumerate(rows):
        xy = np.rint(uv[ci]).astype(int)
        valid = (z[ci]>0) & (xy[:, 0]>=0) & (xy[:, 0]<1920) & (xy[:, 1]>=0) & (xy[:, 1]<1080)
        for masks, order, dest in [(refmasks, refnames, distances), (original_masks, names, original_distances)]:
            dist = signed_distance(masks[order.index(row['physical_camera'])])
            dest[ci, valid] = dist[xy[valid, 1], xy[valid, 0]]
    log_gain = np.load(COLOR/'parameters.npz')['log_gain']
    gains = np.exp(log_gain-log_gain.mean(0, keepdims=True))
    exposure = read(COLOR/'exposure.json')['fixed_exposure_gain']
    cache = {}; source_hashes = {}
    def rgb(ci):
        if ci not in cache:
            row = rows[ci]
            cache[ci] = np.rint(display(exr(row['file_path'])*gains[ci], exposure)*255).clip(0,255).astype(np.uint8)
            source_hashes[row['file_path']] = sha(row['file_path'])
        return cache[ci]
    for si, s in enumerate(active):
        chosen = s['source_id']
        order = np.argsort(np.nan_to_num(distances[:, si], nan=-1e9))
        witnesses = list(dict.fromkeys([chosen, *order[-2:][::-1].tolist(), *order[:2].tolist()]))
        panel = Image.new('RGB', (192*(1+len(witnesses)), 245), (25, 25, 25))
        draw = ImageDraw.Draw(panel)
        x, y = s['portrait_xy']
        panel.paste(Image.fromarray(image).crop((x-90, y-90, x+90, y+90)), (6, 45))
        draw.text((6, 5), f'target {x},{y}', fill='white')
        draw.ellipse((93,132,99,138), outline='red')
        evidence = []
        for wi, ci in enumerate(witnesses):
            u, vv = uv[ci, si]; ix, iy = np.rint([u,vv]).astype(int)
            crop = np.rot90(np.asarray(Image.fromarray(rgb(ci)).crop((ix-90, iy-90, ix+90, iy+90))))
            offset = (wi+1)*192
            panel.paste(Image.fromarray(crop), (offset+6,45))
            draw.text((offset+5, 5), rows[ci]['physical_camera'], fill='white')
            draw.text((offset+5, 19), f'{"CHOSEN" if ci==chosen else "witness"} d={distances[ci,si]:.1f}', fill='white')
            # Rotation maps native (u,v) to portrait (v,179-u).
            px, py = offset+6+90+vv-iy, 45+89-u+ix
            draw.ellipse((px-3, py-3, px+3, py+3), outline='red')
            evidence.append(dict(camera=rows[ci]['physical_camera'], source_id=ci, chosen=ci==chosen,
                uv=uv[ci,si].tolist(), refined_signed_distance=float(distances[ci,si]),
                original_signed_distance=float(original_distances[ci,si])))
        name=f'point_{si:02d}.png';panel.save(folder/name)
        s.update(witnesses=evidence, panel=name, panel_sha256=sha(folder/name),
            refined_inside_cameras=int((distances[:,si]>0).sum()),
            refined_outside_over_4px=int((distances[:,si]<-4).sum()))
    np.savez_compressed(folder/'projections.npz', uv=uv, depth=z,
        refined_signed_distance=distances, original_signed_distance=original_distances)
    atomic_json(folder/'result.json', dict(frame=frame, samples=samples,
        parent_request_sha256=sha(BASE/'request.json'), parent_complete_sha256=sha(source/'complete.json'),
        mesh_path=record['mesh'], mesh_sha256=record['mesh_sha256'], geometry_changed=False,
        heldout_used=False, hand_selected_diagnostic_pixels=True, used_for_geometry=False,
        source_rgb_hashes=source_hashes, script_sha256=sha(__file__),
        masks_sha256=sha(maskroot/'masks.npz'), refined_masks_sha256=sha(refined/'masks.npz'),
        color_parameters_sha256=sha(COLOR/'parameters.npz'), exposure_sha256=sha(COLOR/'exposure.json'),
        projection_sha256=sha(folder/'projections.npz'), seconds=time.monotonic()-start,
        visual_status='pending', mask_votes_not_visibility_certificates=True))
    print('complete', folder, 'samples', len(active), 'seconds', time.monotonic()-start, flush=True)


if __name__ == '__main__':
    argparse.ArgumentParser(description=__doc__).parse_args()
    run()
