"""Explicit, hash-bound local shelf diagnosis; never edits a published candidate.

Screen-space selection is a manually reviewed hypothesis, not independent depth
evidence. Removing a face is only a proposal until real views and the newly
exposed surface are inspected. No inferred surface is generated by this tool.
"""
from __future__ import annotations
import argparse
from copy import deepcopy
from pathlib import Path
import numpy as np
import open3d as o3d
from PIL import Image, ImageDraw
from joint_temporal_texture import read, sha, atomic_json
from diffusion_mesh_repair import scene_for
from bake_joint_temporal_mesh import camera_depth

BASE = Path('/mnt/data/lookcloser_dec5_5a3_smooth_temporal_prior_canary')
OUTPUT = Path('/mnt/data/lookcloser_dec5_5a3_shelf_diagnosis_000971')
BOX = (320, 1040, 460, 1140)


def inputs(base, frame):
    request = read(base/'request.json')
    record = next(r for r in request['inventory'] if r['frame_id'] == frame)
    if sha(record['mesh']) != record['mesh_sha256']:
        raise ValueError('Original geometry checksum mismatch')
    mesh = o3d.io.read_triangle_mesh(record['mesh'])
    return request, record, mesh


def inspect(base, output, frame):
    request, record, mesh = inputs(base, frame)
    output.mkdir(parents=True, exist_ok=True)
    provenance = {'base': str(base), 'frame_id': frame, 'request_sha256': sha(base/'request.json'),
                  'mesh_sha256': record['mesh_sha256'], 'crop_portrait': BOX,
                  'render_sha256': sha(base/'frames'/frame/'frame.png')}
    if (output/'diagnosis_request.json').exists() and read(output/'diagnosis_request.json') != read_json_roundtrip(provenance):
        raise ValueError('Diagnosis provenance changed')
    atomic_json(output/'diagnosis_request.json', provenance)
    v, t = np.asarray(mesh.vertices), np.asarray(mesh.triangles)
    d, ids, _ = camera_depth(scene_for(v, t), record['camera'])
    d, ids = np.rot90(d), np.rot90(ids)
    np.savez_compressed(output/'raycast_portrait.npz', depth=d, ids=ids)
    rgb = Image.open(base/'frames'/frame/'frame.png').convert('RGB')
    crop = rgb.crop(BOX).resize((560,400), Image.Resampling.NEAREST)
    crop.save(output/'before_detail.png')
    rng = np.random.default_rng(971)
    colors = rng.integers(40,240,(len(t)+1,3),dtype=np.uint8)
    safe = np.where(ids < len(t), ids, len(t))
    colors[-1] = 0
    wire = Image.fromarray(colors[safe]).crop(BOX).resize((560,400), Image.Resampling.NEAREST)
    wire.save(output/'triangle_detail.png')
    x0,y0,x1,y1 = BOX
    unique, counts = np.unique(ids[y0:y1,x0:x1], return_counts=True)
    center = v[t].mean(1)
    atomic_json(output/'visible_faces.json', [{'id': int(f), 'pixels': int(n), 'centroid': center[f].tolist()}
                for f,n in zip(unique,counts) if f < len(t)])
    print(f'frame={frame} mesh_triangles={len(t)} roi_faces={len(unique)}', flush=True)


def read_json_roundtrip(value):
    import json
    return json.loads(json.dumps(value))


def select_contained_faces(ids, polygon, triangle_count, min_fraction=.9):
    """Reject broad edits: selected faces must lie almost entirely inside review ROI."""
    mask = Image.new('L', (ids.shape[1], ids.shape[0]))
    ImageDraw.Draw(mask).polygon([tuple(p) for p in polygon], fill=1)
    mask = np.asarray(mask).astype(bool)
    valid = ids < triangle_count
    total = np.bincount(ids[valid].astype(np.int64), minlength=triangle_count)
    inside = np.bincount(ids[valid & mask].astype(np.int64), minlength=triangle_count)
    selection = (inside > 0) & (inside >= min_fraction*np.maximum(total,1))
    return np.flatnonzero(selection), mask


def propose(base, output, frame, selection_path):
    request, record, mesh = inputs(base, frame)
    selection = read(selection_path)
    if selection['mesh_sha256'] != record['mesh_sha256'] or selection['render_sha256'] != sha(base/'frames'/frame/'frame.png'):
        raise ValueError('Manual selection is not bound to the actual mesh and render')
    v, t = np.asarray(mesh.vertices), np.asarray(mesh.triangles)
    raycast = np.load(output/'raycast_portrait.npz')
    ids, before = raycast['ids'], raycast['depth']
    selected, mask = select_contained_faces(ids, selection['polygon_portrait'], len(t), selection.get('min_fraction', .9))
    if 'explicit_face_ids' in selection:
        explicit = np.asarray(selection['explicit_face_ids'], dtype=np.int64)
        if len(np.unique(explicit)) != len(explicit) or not np.isin(explicit, selected).all():
            raise ValueError('Explicit faces must be unique and inside the reviewed selection')
        selected = explicit
    if not 0 < len(selected) <= 100:
        raise ValueError(f'Unexpected local edit extent: {len(selected)} faces')
    keep = np.ones(len(t), bool); keep[selected] = False
    variant = output/selection_path.stem
    if (variant/'request.json').exists():
        raise ValueError('Existing proposal is immutable; use a new selection name')
    variant.mkdir(exist_ok=True)
    candidate = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(v), o3d.utility.Vector3iVector(t[keep]))
    o3d.io.write_triangle_mesh(str(variant/'mesh.ply'), candidate)
    after, _, _ = camera_depth(scene_for(v,t[keep]), record['camera'])
    after = np.rot90(after)
    removed_pixels = np.isin(ids,selected)
    behind = removed_pixels & np.isfinite(after)
    delta = after[behind]-before[behind]
    report = {'selected_faces': selected.tolist(), 'removed_face_count': len(selected),
              'removed_visible_pixels': int(removed_pixels.sum()), 'new_hole_pixels': int((removed_pixels & ~np.isfinite(after)).sum()),
              'underlying_hit_pixels': int(behind.sum()), 'depth_delta_min_median_max': np.quantile(delta,[0,.5,1]).tolist() if len(delta) else [],
              'underlying_surface_is_independently_verified': False, 'manual_proposal_not_measurement': True,
              'selection_sha256': sha(selection_path), 'mesh_sha256': sha(variant/'mesh.ply'),
              'original_mesh_sha256':record['mesh_sha256'], 'all_original_vertices_unchanged': True,
              'outside_selected_triangle_inventory_unchanged': True}
    atomic_json(variant/'geometry_diagnostic.json',report)
    Image.fromarray((removed_pixels*255).astype(np.uint8)).crop(BOX).resize((560,400),Image.Resampling.NEAREST).save(variant/'removed_pixels.png')
    np.savez_compressed(variant/'target_depth_diagnostic.npz',before=before,after=after,removed_pixels=removed_pixels)
    reduced = deepcopy(request)
    reduced['ordered_frame_ids'] = [frame]
    reduced['source_rows'] = [r for r in request['source_rows'] if Path(r['source_dataset']).name == frame]
    row = deepcopy(record); row.update(mesh=str(variant/'mesh.ply'),mesh_sha256=report['mesh_sha256'])
    reduced['inventory'] = [row]
    reduced['recipe'].update(frames=1, experiment='manual_shelf_removal_proposal', parent_request_sha256=sha(base/'request.json'),
                             selection_sha256=sha(selection_path), independent_geometry_validation_required=True)
    reduced['script_hashes'][Path(__file__).name] = sha(__file__)
    if (variant/'request.json').exists() and read(variant/'request.json') != reduced:
        raise ValueError('Immutable proposal request mismatch')
    atomic_json(variant/'request.json',reduced)
    (variant/'frames').mkdir(exist_ok=True)
    print(report,flush=True)


def comparison(base, output, frame):
    """Native and 4x nearest diagnostic only; no prediction pixels are edited."""
    before = Image.open(base/'frames'/frame/'frame.png').convert('RGB')
    after = Image.open(output/'frames'/frame/'frame.png').convert('RGB')
    sheet = Image.new('RGB',(1120,430))
    for i, (im,title) in enumerate([(before,'Original'),(after,'Local removal proposal')]):
        sheet.paste(im.crop(BOX).resize((560,400),Image.Resampling.NEAREST),(i*560,30))
        ImageDraw.Draw(sheet).text((i*560+5,8), title,fill='white')
    sheet.save(output/'comparison_detail.png')
    large = Image.new('RGB',(900,450))
    box=(280,970,730,1420)
    large.paste(before.crop(box),(0,0));large.paste(after.crop(box),(450,0))
    large.save(output/'comparison_lipstick_hand.png')
    a,b=np.asarray(before),np.asarray(after)
    changed=(a!=b).any(-1)
    atomic_json(output/'rgb_change_diagnostic.json',{'changed_pixels':int(changed.sum()),
                'max_channel_change':int(np.abs(a.astype(int)-b).max()),
                'note':'Graph relabeling can change RGB outside edited geometry. Must inspect before acceptance.'})


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('action',choices=['inspect','propose','render','compare'])
    p.add_argument('--base',type=Path,default=BASE);p.add_argument('--output',type=Path,default=OUTPUT)
    p.add_argument('--frame',default='000971');p.add_argument('--selection',type=Path)
    a=p.parse_args()
    if a.action=='inspect':inspect(a.base,a.output,a.frame)
    elif a.action=='propose':
        if a.selection is None:p.error('--selection required')
        propose(a.base,a.output,a.frame,a.selection)
    elif a.action=='compare':comparison(a.base,a.output,a.frame)
    else:
        import render_smooth_temporal_mesh_video as renderer
        from temporal_texture_view_prior import install
        renderer.torch.set_num_threads(4);install(renderer);renderer.render(a.output,[a.frame])
        comparison(a.base,a.output,a.frame)


if __name__=='__main__':main()
